### ISSUE TITLE
README の画像ファイル表示がエラーになっている

### ISSUE THREAD

**Issue by johnta0** [JYama321/diary-app#2]
README の、 diary-app ER 図がエラーになって表示されていない。画像プロキシのエラー。

https://camo.githubusercontent.com/602e860e3db58ef62a97f33e55060813d2402c97/68747470733a2f2f73332d61702d6e6f727468656173742d312e616d617a6f6e6177732e636f6d2f6a69726f2d707269766174652d706963732f64696172792d6170705f64622e706e67

**Comment by JYama321** [comment]
fixed, Thank you so much!
